/**
 * Do not edit this file except you know what you are doing. :]
 */

import { defineConfig } from "vite";
import path from "path";
import fs from "fs";

const devHotFile = () => {
  const hotFilePath = path.resolve(__dirname, "public/build/hot");

  return {
    name: "hot",

    configureServer(server) {
      fs.writeFileSync(
        hotFilePath,
        `http://localhost:${server.config.server.port}`
      );

      const clean = () => {
        if (fs.existsSync(hotFilePath)) {
          fs.unlinkSync(hotFilePath);
        }
      };

      process.on("exit", clean);
      process.on("SIGINT", clean);
      process.on("SIGTERM", clean);
    },
  };
};

export default defineConfig(({ command }) => ({
  root: "src",
  base: "/build/",
  build: {
    manifest: true,
    outDir: path.resolve(__dirname, "public/build"),
    emptyOutDir: true,
    rollupOptions: {
      input: {
        app: "src/app.ts",
      },
    },
  },
  plugins: command === "serve" ? [devHotFile()] : [],
}));
